# Site settings
title: EruBlog
description: >- # this means to ignore newlines until "baseurl:"
  This is a blog build with Jekyll and using jekyll-theme-hacker with some modifications and additions to suit my needs. Hosted by GitHub Pages.
author: "Erus"
email:
url: "https://erudin.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
show_downloads: false

# Social settings
github_username: erudin
rss: rss
# twitter_username:
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
# linkedin_username:
# pinterest_username:
# youtube_username:
# youtube_channel:
# youtube_channel_name:
# telegram_username:
# googleplus_username:
# microdotblog_username:

# Mastodon instances
# mastodon:
# - username:
#   instance: example.com
# - username:
#   instance: example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
paginate: 3
paginate_path: "/page/:num/"

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Erus"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Custom variables
owner : "Erus"
year : "2018"
